/*
Copyright 2017 Turbine Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Automatically generated by MockGen. DO NOT EDIT!
// Source: admin_server.go

package adminserver

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of AdminServer interface
type MockAdminServer struct {
	ctrl     *gomock.Controller
	recorder *_MockAdminServerRecorder
}

// Recorder for MockAdminServer (not exported)
type _MockAdminServerRecorder struct {
	mock *MockAdminServer
}

func NewMockAdminServer(ctrl *gomock.Controller) *MockAdminServer {
	mock := &MockAdminServer{ctrl: ctrl}
	mock.recorder = &_MockAdminServerRecorder{mock}
	return mock
}

func (_m *MockAdminServer) EXPECT() *_MockAdminServerRecorder {
	return _m.recorder
}

func (_m *MockAdminServer) Start() error {
	ret := _m.ctrl.Call(_m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAdminServerRecorder) Start() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Start")
}

func (_m *MockAdminServer) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAdminServerRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockAdminServer) Listening() bool {
	ret := _m.ctrl.Call(_m, "Listening")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockAdminServerRecorder) Listening() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Listening")
}

func (_m *MockAdminServer) Addr() string {
	ret := _m.ctrl.Call(_m, "Addr")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockAdminServerRecorder) Addr() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Addr")
}

func (_m *MockAdminServer) LastRequestedSignal() RequestedSignalType {
	ret := _m.ctrl.Call(_m, "LastRequestedSignal")
	ret0, _ := ret[0].(RequestedSignalType)
	return ret0
}

func (_mr *_MockAdminServerRecorder) LastRequestedSignal() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LastRequestedSignal")
}
