// Automatically generated by MockGen. DO NOT EDIT!
// Source: fromflags.go

package main

import (
	gomock "github.com/golang/mock/gomock"
	nginxconfig "github.com/turbinelabs/agent/confagent/nginxconfig"
	proc "github.com/turbinelabs/proc"
)

// Mock of FromFlags interface
type MockFromFlags struct {
	ctrl     *gomock.Controller
	recorder *_MockFromFlagsRecorder
}

// Recorder for MockFromFlags (not exported)
type _MockFromFlagsRecorder struct {
	mock *MockFromFlags
}

func NewMockFromFlags(ctrl *gomock.Controller) *MockFromFlags {
	mock := &MockFromFlags{ctrl: ctrl}
	mock.recorder = &_MockFromFlagsRecorder{mock}
	return mock
}

func (_m *MockFromFlags) EXPECT() *_MockFromFlagsRecorder {
	return _m.recorder
}

func (_m *MockFromFlags) Validate() error {
	ret := _m.ctrl.Call(_m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFromFlagsRecorder) Validate() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Validate")
}

func (_m *MockFromFlags) MakeNginxConfig(reload reloader) nginxconfig.NginxConfig {
	ret := _m.ctrl.Call(_m, "MakeNginxConfig", reload)
	ret0, _ := ret[0].(nginxconfig.NginxConfig)
	return ret0
}

func (_mr *_MockFromFlagsRecorder) MakeNginxConfig(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MakeNginxConfig", arg0)
}

func (_m *MockFromFlags) MakeManagedProc(onExit func(error), args []string) proc.ManagedProc {
	ret := _m.ctrl.Call(_m, "MakeManagedProc", onExit, args)
	ret0, _ := ret[0].(proc.ManagedProc)
	return ret0
}

func (_mr *_MockFromFlagsRecorder) MakeManagedProc(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MakeManagedProc", arg0, arg1)
}
